[project]
name = "excel-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.1",
 "pandas>=2.0.0",
 "openpyxl>=3.1.0",
 "swifter>=1.4.0",
]
